name: crypto_wallet
description: A crypto wallet centralizer.
publish_to: 'none'
version: 0.9.6+0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adaptive_theme: ^3.4.1
  cloud_firestore: ^4.13.3
  dropdown_search: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_slidable: ^3.0.1
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  google_fonts: ^6.1.0
  google_mobile_ads: ^3.1.0
  google_sign_in: ^6.1.6
  http: ^1.1.2
  intl: ^0.18.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_cloud_firestore: ^2.4.4
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true