name: crypto_wallet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.14.0
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.2.0+2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  google_mobile_ads: ^4.0.0
  http: ^1.2.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  mobx: ^2.3.0+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  json_serializable: ^6.7.1


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svgs/

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: pt
  arb_dir: assets/l10n/arb/
  output_dir: lib/core/l10n/
  use_deferred_loading: true
