name: CI/CD

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

jobs:
  # flutter_test:
  #   name: Run Flutter analyze and test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@1
  #       with:
  #         java-version: "12.x"
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: "stable"
  #     - run: flutter pub get
  #     - run: flutter analyze
  #     - run: flutter format --dry-run --set-exit-if-changed lib/ 
  #     - run: flutter format --dry-run --set-exit-if-changed test/
  #     - run: flutter test --coverage
  #     - run: flutter test -machine > test-results.json

  #     # Generate a test report
  #     - uses: dorny/test-reporter@1.4.2
  #       with:
  #         name: test-results
  #         path: test-results.json
  #         reporter: flutter-json
          
  #     # Define the min converage for tests
  #     - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
  #       with:
  #         min_coverage: 0 

  build_ios:
    name: Build (iOS)
    # needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter pub clean
      - run: flutter pub build ios -t lib/main_dev.dart --release --no-codesign

  build_android:
    name: Build (Andorid)
    # needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter pub clean
      - run: flutter build apk -t lib/main_dev.dart --build-number=0 --build-name=1.0.0

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v2.1.4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk