/// List all cryptos that are supported by the system
abstract class Cryptos {
  ///Map of coin colors in the app
  static const Map<String, int> colors = {
    'bitcoin': 0xFFF79319,
    'ethereum': 0xFF686f95,
    'cardano': 0xFF26508C,
    'binancecoin': 0xFFF3BA2F,
    'tether': 0xFF05AD85,
    'ripple': 0xFF5B5F64,
    'dogecoin': 0xFFBB9F36,
    'usd-coin': 0xFF2674C9,
    'polkadot': 0xFF343335,
    'solana': 0xFF8775DB,
    'uniswap': 0xFFFE1A87,
    'bitcoin-cash': 0xFF0AC18E,
    'binance-usd': 0xFFEDB70B,
    'terra-luna': 0xFFFFD952,
    'chainlink': 0xFF2E52AF,
    'litecoin': 0xFF222222,
    'internet-computer': 0xFF28A9E0,
    'matic-network': 0xFF8247E5,
    'wrapped-bitcoin': 0xFFF79319,
    'vechain': 0xFF4284BC,
    'stellar': 0xFF0F0F0F,
    'theta-token': 0xFFB1EBED,
    'ethereum-classic': 0xFF168F1A,
    'filecoin': 0xFF0090FF,
    'tron': 0xFFC12F26,
    'coti': 0xFF2D65B0,
    'avalanche-2': 0xFFE84142,
    'cosmos': 0xFF2B2E46,
  };

  ///List of ids of the coins in the app
  static const List<String> list = [
    'bitcoin',
    'ethereum',
    'cardano',
    'binancecoin',
    'tether',
    'ripple',
    'dogecoin',
    'polkadot',
    'solana',
    'usd-coin',
    'uniswap',
    'chainlink',
    'terra-luna',
    'binance-usd',
    'bitcoin-cash',
    'litecoin',
    'internet-computer',
    'wrapped-bitcoin',
    'matic-network',
    'vechain',
    'ethereum-classic',
    'stellar',
    'filecoin',
    'avalanche-2',
    'theta-token',
    'cosmos',
    'compound-ether',
    'ftx-token',
    'tron',
    'okb',
    'dai',
    'monero',
    'pancakeswap-token',
    'aave',
    'eos',
    'compound-usd-coin',
    'the-graph',
    'tezos',
    'cdai',
    'staked-ether',
    'axie-infinity',
    'klay-token',
    'crypto-com-chain',
    'algorand',
    'neo',
    'shiba-inu',
    'elrond-erd-2',
    'kusama',
    'bitcoin-cash-abc-2',
    'maker',
    'iota',
    'bitcoin-cash-sv',
    'bittorrent-2',
    'waves',
    'leo-token',
    'thorchain',
    'amp-token',
    'arweave',
    'sushi',
    'huobi-token',
    'hedera-hashgraph',
    'compound-governance-token',
    'dash',
    'decred',
    'near',
    'quant-network',
    'terrausd',
    'celsius-degree-token',
    'helium',
    'fantom',
    'havven',
    'chiliz',
    'huobi-btc',
    'holotoken',
    'enjincoin',
    'xdce-crowd-sale',
    'theta-fuel',
    'nem',
    'zcash',
    'blockstack',
    'flow',
    'true-usd',
    'zilliqa',
    'yearn-finance',
    'safemoon',
    'qtum',
    'bitcoin-gold',
    'decentraland',
    'ravencoin',
    'harmony',
    'telcoin',
    'basic-attention-token',
    'xsushi',
    'kucoin-shares',
    'nexo',
    'zencash',
    'bancor',
    'siacoin',
    'audius',
    'nxm',
    'link',
    'iostoken',
    'digibyte',
    'paxos-standard',
    'ontology',
    'icon',
    'perpetual-protocol',
    '0x',
    'mdex',
    'omisego',
    'curve-dao-token',
    'the-sandbox',
    'nano',
    'coin98',
    'mina-protocol',
    'ecomi',
    'uma',
    'compound-usdt',
    'celo',
    'ankr',
    'constellation-labs',
    'ultra',
    'ergo',
    'swissborg',
    'yield-guild-games',
    'republic-protocol',
    'renbtc',
    'gatechain-token',
    'raydium',
    'kava',
    'iotex',
    'swipe',
    'bitclout',
    'titanswap',
    'wazirx',
    'loopring',
    'osmosis',
    'reserve-rights-token',
    'eden',
    'pirate-chain',
    'dent',
    'liquity-usd',
    '1inch',
    'lisk',
    'bakerytoken',
    'unibright',
    'wax',
    'alpha-finance',
    'livepeer',
    'golem',
    'wink',
    'skale',
    'vethor-token',
    'bitcoin-diamond',
    'fetch-ai',
    'neutrino',
    'pundi-x-2',
    'verge',
    'gnosis',
    'energy-web-token',
    'husd',
    'injective-protocol',
    'olympus',
    'medibloc',
    'serum',
    'nervos-network',
    'alien-worlds',
    'fx-coin',
    'pundi-x',
    'oxygen',
    'fei-protocol',
    'origin-protocol',
    'seth',
    'ocean-protocol',
    'status',
    'venus',
    'trust-wallet-token',
    'mango-markets',
    'tribe-2',
    'persistence',
    'chia',
    'anchor-protocol',
    'mask-network',
    'compound-uniswap',
    'iexec-rlc',
    'band-protocol',
    'tokamak-network',
    'balancer',
    'illuvium',
    'bifrost',
    'cartesi',
    'pax-gold',
    'storm',
    'rocket-pool',
    'reef-finance',
    'marketpeak',
    'polymath',
    'mirror-protocol',
    'my-neighbor-alice',
    'frax',
    'celer-network',
    'funfair',
    'prometeus',
    'radicle',
    'asd',
    'dodo',
    'nkn',
    'dawn-protocol',
    'ardor',
    'nusd',
    'woo-network',
    'coti',
    'superrare',
    'derivadao',
    'alchemix',
    'ellipsis',
    'akash-network',
    'metal',
    'tomochain',
    'orbs',
    'superfarm',
    'conflux-token',
    'numeraire',
    'orion-protocol',
    'electroneum',
    'apeswap-finance',
    'verasity',
    'bonfida',
    'truefi',
    'klever',
    'chromaway',
    'mobox',
    'hbtc-token',
    'stratis',
    'smooth-love-potion',
    'ton-crystal',
    'keep-network',
    'badger-dao',
    'velas',
    'orchid-protocol',
    'maidsafecoin',
    'alchemix-usd',
    'vectorspace',
    'thorstarter',
    'automata',
    'steem',
    'yfii-finance',
    'secret',
    'civic',
    'sapphire',
    'lido-dao',
    'clover-finance',
    'ark',
    'frax-share',
    'playdapp',
    'render-token',
    'ethlend',
    'aelf',
    'quick',
    'storj',
    'allianceblock',
    'token-pocket',
    'defipulse-index',
    'zkswap',
    'metadium',
    'math',
    'hive',
    'sbtc',
    'noia-network',
    'kyber-network-crystal',
    'gemini-dollar',
    'tokocrypto',
    'utrust',
    'convex-crv',
    'gala',
    'hathor',
    'aragon',
    'api3',
    'oasis-network',
    'rif-token',
    'singularitynet',
    'lukso-token',
    'tokemak',
    'starlink',
    'digitalbits',
    'augur',
    'wanchain',
    'plex',
    'alchemy-pay',
    'ethernity-chain',
    'concierge-io',
    'kyber-network',
    'alpaca-finance',
    'nucypher',
    'kin',
    'request-network',
    'everipedia',
    'ankreth',
    'gitcoin',
    'uquid-coin',
    'rally-2',
    'metahero',
    'wrapped-nxm',
    'thorchain-erc20',
    'safepal',
    'linear',
    'casper-network',
    'feg-token',
    'melon',
    'bitshares',
    'btc-standard-hashrate-token',
    'auction',
    'crypto20',
    'sun-token',
    'ampleforth-governance-token',
    'covalent',
    'certik',
    'rari-governance-token',
    'beldex',
    'harvest-finance',
    'tether-gold',
    'convex-finance',
    'eth-2x-flexible-leverage-index',
    'quark-chain',
    'komodo',
    'syscoin',
    'pha',
    'ampleforth',
    'kirobo',
    'instadapp',
    'hxro',
    'polkastarter',
    'telos',
    'litentry',
    'power-ledger',
    'gas',
    'district0x',
    'flex-coin',
    'wilder-world',
    'kardiachain',
    'vai',
    'compound-0x',
    'terra-virtua-kolect',
    'artery',
    'usdp',
    'origintrail',
    'escoin-token',
    'ledgis',
    'bytom',
    'usdx',
    'newscrypto-coin',
    'privateum',
    'sentinel',
    'whale',
    'cream-2',
    'xyo-network',
    'handshake',
    'monacoin',
    'dero',
    'iris-network',
    'rook',
    'zipmex-token',
    'ptokens-btc',
    'rarible',
    'cardstarter',
    'mx-token',
    'the-truth',
    'cvault-finance',
    'dao-maker',
    'wrapped-centrifuge',
    'mainframe',
    'sonm',
    'bella-protocol',
    'axia-coin',
    'barnbridge',
    'wozx',
    'bzx-protocol',
    'tenset',
    'e-radix',
    'unit-protocol',
    'hydra',
    'waves-ducks',
    'kadena',
    'just',
    'decentral-games',
    'sora-validator-token',
    'compound-basic-attention-token',
    'divi',
    'tellor',
    'aavegotchi',
    'hi-dollar',
    'ramp',
    'zcoin',
    'lockchain',
    'sora',
    'stasis-eurs',
    'streamr-xdata',
    '3x-long-ethereum-token',
    'carry',
    'crust-network',
    'dia-data',
    'friends-with-benefits-pro',
    'evolution-finance',
    'hegic',
    'nerve-finance',
    'redfox-labs-2',
    'unfederalreserve',
    'adax',
    'aion',
    'joe',
    'plant-vs-undead-token',
    'paccoin',
    'wpp-token',
    'seth2',
    'legolas-exchange',
    'nftx',
    'pylon-protocol',
    'paris-saint-germain-fan-token',
    'unizen',
    'vulcan-forged',
    'occamfi',
    'index-cooperative',
    'mxc',
    'kleros',
    'akropolis',
    'thunder-token',
    'strong',
    'chain-games',
    'contentos',
    'dvision-network',
    'gerowallet',
    'lto-network',
    'nominex',
    'sharering',
    'parsiq',
    'loom-network',
    'trustswap',
    'seur',
    'hard-protocol',
    'boringdao-btc',
    'populous',
    'haven',
    'dextools',
    'tornado-cash',
    'keep3rv1',
    'beefy-finance',
    'paid-network',
    'insure',
    'woonkly-power',
    'videocoin',
    'velo',
    'stakehound-staked-ether',
    'mcdex',
    'bepro-network',
    'cream-eth2',
    'bluzelle',
    'yooshi',
    'arpa-chain',
    'groestlcoin',
    'anyswap',
    'mantra-dao',
    'stp-network',
    'stablexswap',
    'cobak-token',
    'get-token',
    'fio-protocol',
    'energi',
    'btse-token',
    'refereum',
    'reddcoin',
    'manchester-city-fan-token',
    'maps',
    'pangolin',
    'verus-coin',
    'atari',
    'slink',
    'lgcy-network',
    'zero-collateral-dai',
    'futureswap',
    'openocean',
    'adex',
    'marinade-staked-sol',
    'dock',
    'morpheus-network',
    'tokenlon',
    'suku',
    'steem-dollars',
    'governance-zil',
    'bytecoin',
    'sentinel-protocol',
    'gny',
    'vite',
    'epik-protocol',
    'marlin',
    'zenon',
    'aergo',
    'universe-xyz',
    'kine-protocol',
    'alchemist',
    'polkadex',
    'lbry-credits',
  ];

// * The code above will be used if change the app to use the Messari API or another one which doesn't have image
//  static Map<String, Crypto> cryptos = {
//     'bitcoin': Crypto('bitcoin', 'https://assets.coingecko.com/coins/images/1/thumb/bitcoin.png?1547033579', 0xFFF79319),
//     'ethereum': Crypto('ethereum', 'https://assets.coingecko.com/coins/images/279/thumb/ethereum.png?1595348880', 0xFF686f95),
//     'cardano': Crypto('cardano', 'https://assets.coingecko.com/coins/images/975/thumb/cardano.png?1547034860', 0xFF26508C),
//     'binancecoin': Crypto('binancecoin', 'https://assets.coingecko.com/coins/images/825/thumb/binance-coin-logo.png?1547034615', 0xFFF3BA2F),
//     'tether': Crypto('tether', 'https://assets.coingecko.com/coins/images/325/thumb/Tether-logo.png?1598003707', 0xFF05AD85),
//     'ripple': Crypto('ripple', 'https://assets.coingecko.com/coins/images/44/thumb/xrp-symbol-white-128.png?1605778731', 0xFF5B5F64),
//     'dogecoin': Crypto('dogecoin', 'https://assets.coingecko.com/coins/images/5/thumb/dogecoin.png?1547792256', 0xFFBB9F36),
//     'polkadot': Crypto('polkadot', 'https://assets.coingecko.com/coins/images/12171/thumb/aJGBjJFU_400x400.jpg?1597804776', 0xFF343335),
//     'solana': Crypto('solana', 'https://assets.coingecko.com/coins/images/4128/thumb/Solana.jpg?1635329178', 0xFF8775DB),
//     'usd-coin': Crypto('usd-coin', '', 0xFF2674C9),
//     'uniswap': Crypto('uniswap', '', 0xFFFE1A87),
//     'chainlink': Crypto('chainlink', '', 0xFF2E52AF),
//     'terra-luna': Crypto('terra-luna', '', 0xFFFFD952),
//     'binance-usd': Crypto('binance-usd', '', 0xFFEDB70B),
//     'bitcoin-cash': Crypto('bitcoin-cash', '', 0xFF0AC18E),
//     'litecoin': Crypto('litecoin', '', 0xFF222222),
//     'internet-computer': Crypto('internet-computer', '', 0xFF28A9E0),
//     'matic-network': Crypto('matic-network', '', 0xFF8247E5),
//     'wrapped-bitcoin': Crypto('wrapped-bitcoin', '', 0xFFF79319),
//     'vechain': Crypto('vechain', '', 0xFF4284BC),
//     'stellar': Crypto('stellar', '', 0xFF0F0F0F),
//     'theta-token': Crypto('theta-token', '', 0xFFB1EBED),
//     'ethereum-classic': Crypto('ethereum-classic', '', 0xFF168F1A),
//     'filecoin': Crypto('filecoin', '', 0xFF0090FF),
//     'tron': Crypto('tron', '', 0xFFC12F26),
//     'coti': Crypto('coti', '', 0xFF2D65B0),
//     'avalanche': Crypto('avalanche', '', 0xFFE84142),
//     'cosmos': Crypto('cosmos', '', 0xFF2B2E46),
//   };

}


// class Crypto {
//   String id;
//   String image;
//   int color;

//   Crypto(this.id, this.image, int? color) : this.color = color ?? 0xFF424A57;
// }

